### ISSUE TITLE
Change findAndModify  by findOneAndUpdate

### ISSUE THREAD

**Issue by michaelmontero** [daton89-topperblues/mongoose-transactions#17]
(node:4252) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
warning.js:18
(node:4252) DeprecationWarning: collection.findAndModify is deprecated. Use findOneAndUpdate, findOneAndReplace or findOneAndDelete instead.
warning.js:18
(node:4252) UnhandledPromiseRejectionWarning: #<Object>
warning.js:18
(node:4252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
warning.js:18
(node:4252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
warning.js:18

**Comment by topperblues** [comment]
Fixed by @daton89 with commit 91763c3e9bd7536e869c5d868269d884f46603a2
