### ISSUE TITLE
mongoose-transactions retrieve results that are saved in DB?

### ISSUE THREAD

**Issue by createbuildship** [daton89-topperblues/mongoose-transactions#18]
Doing 
        const userId = transaction.insert(A, user);
        const websiteId = transaction.insert(B, website)
        const pageId = transaction.insert(C, page);
        transaction.update(B, websiteId, { name: 'bravo'})
        const final = await transaction.run();
        const operations = transaction.getOperations();
        transaction.clean();

I get in the const final all 4 operations ( 3 inserts and 1  update).
the object that has update  has a new ID.

can I just return the saved new 3 objects and how do I do it?

**Comment by daton89** [comment]
I don't know what you are trying to achieve, maybe filter the operations?
