### ISSUE TITLE
Create new Document after rollback

### ISSUE THREAD

**Issue by hoanglecao** [daton89-topperblues/mongoose-transactions#22]
My document structure as below
 ModeSchema: Schema = new Schema({
        key: String,
        specificationNumber: String,
        inactiveVersions: Array,
        endApprovalDate: Date,
        lastUpdated: Date,
        lastUpdatedBy: String,
        status: String,
        name: String,
        type: String,
        limit: Number,
        minimumPRPTPercentage: Number,
        maximumPRPTPercentage: Number,
        comments: String,
    },
    {
        timestamps: true,
    }
);

After using transaction.remove and rollback, the system created a new document with fields: _id, updatedAt, createdAt.

I am not sure what I am missing. Could you help me have a look on this?

Thanks

**Comment by topperblues** [comment]
Yes, we could help you.
In your code we can see only the schema/model used with the transaction, to help you, we need the complete code you write for:
- transaction creation
- transaction operation
- transaction run
- transaction rollback

**Comment by daton89** [comment]
I don't think this is an issue, please ask help on stackoverflow for non issues.
