### ISSUE TITLE
Getting error at "await transaction run" while doing a "npm start"

### ISSUE THREAD

**Issue by debabarik100** [daton89-topperblues/mongoose-transactions#4]
**What I am trying to do**
1. Update order status for a given Order ID
2. Update available quantity of the products by deducting the selected amount in the order. The order can have multiple products in it, hence the for loop below

**My Code**
var Transaction = require('mongoose-transactions');
                                    var transaction = new Transaction();
                                    try {
                                        var OrderObjectId = require('mongoose').Types.ObjectId;
                                        order2Update.orderStatus = req.body.orderStatus;
                                        transaction.update('Order', new OrderObjectId(order2Update._id), order2Update);

                                        var ProductObjectId = require('mongoose').Types.ObjectId;
                                        product2Update.totalQuantity = parseFloat(product2Update.totalQuantity) - parseFloat(order2Update.orderList[i].selectedQuantity);
                                        transaction.update('Product', new ProductObjectId(product2Update._id), product2Update);

                                        var final = await transaction.run();
                                    }
                                    catch (error) {
                                        var rollbackObj = await transaction.rollback().catch(console.error);
                                        transaction.clean();
                                    }

**Issue**
When I fire "npm start", it fails with below error

var final = await transaction.run();
                  ^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<code location>)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Environment**
node v6.10.3
npm 3.10.10

**Comment by daton89** [comment]
@debabarik100 node 6 unfortunately does not allow you to use async await feature.

async await feature is present starting by node version 7

The purpose of async/await functions is to simplify the behavior of using promises synchronously and to perform some behavior on a group of Promises. Just as Promises are similar to structured callbacks, async/await is similar to combining generators and promises.

You can simply run transaction working with Promises like so:

```js
var Transaction = require('mongoose-transactions');
var transaction = new Transaction();


var OrderObjectId = require('mongoose').Types.ObjectId;
order2Update.orderStatus = req.body.orderStatus;
transaction.update('Order', new OrderObjectId(order2Update._id), order2Update);
var ProductObjectId = require('mongoose').Types.ObjectId;
product2Update.totalQuantity = parseFloat(product2Update.totalQuantity) - parseFloat(order2Update.orderList[i].selectedQuantity);
transaction.update('Product', new ProductObjectId(product2Update._id), product2Update);

transaction.run()
    .then((final) => {
        console.log('final =>', final);
    })
    .catch((err) => {
        transaction.rollback()
            .then((rolled) => {
                console.log('rolled =>', rolled);
                transaction.clean();
            })
            .catch(console.error)
      
    })
```

**Comment by topperblues** [comment]
I think the solution posted by @daton89 solve the problem

**Comment by MarsZone** [comment]
very useful.
