### ISSUE TITLE
Schema not registered

### ISSUE THREAD

**Issue by KaeyangTheG** [daton89-topperblues/mongoose-transactions#7]
Getting schema not registered error when invoking new Transaction().update('modelName', id, update).  In the same code block the same mongoose model is being used fine so I'm not sure what's wrong here.

**Comment by daton89** [comment]
hi @KaeyangTheG ,
could you check if the modelName you used is the same name with which you registered the model?
if you do not show me an example I don't know how to help you

**Comment by topperblues** [comment]
This issue is closed due to inactivity

**Comment by daton89** [comment]
hi @KaeyangTheG 
thank you for the report
i've correct that problem and i've updated the module... now latest version is 1.1.1
try run: npm uninstall mongoose-transactions -S && npm install mongoose-transactions -S
is it fixed now?
